name: Validate Token Submission

on:
  pull_request:
    paths:
      - 'tokens/80094.json'

# Add permissions block
permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Validate token list format
        run: pnpm run validate

      - name: Generate PR description
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const { execSync } = require('child_process');

            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const tokenFile = files.find(f => f.filename === 'tokens/80094.json');
            if (!tokenFile) {
              core.setFailed('No changes to token list found');
              return;
            }
            
            // Get the changes
            const { data: content } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'tokens/80094.json',
              ref: context.sha
            });
            
            // Save the content to a temporary file
            fs.writeFileSync('tokens/80094.json.new', Buffer.from(content.content, 'base64').toString());
            
            try {
              // Get the base branch content
              const { data: baseContent } = await github.rest.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'tokens/80094.json',
                ref: context.payload.pull_request.base.sha
              });

              // Save the base content to a file
              fs.writeFileSync('tokens/80094.json', Buffer.from(baseContent.content, 'base64').toString());
              
              // Generate PR description
              const description = execSync('pnpm run generate-pr-from-list tokens/80094.json tokens/80094.json.new', { encoding: 'utf8' });
              
              // Always update the PR description with the generated template
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: description
              });
              core.info('Updated PR description with generated template');
            } catch (error) {
              core.setFailed('Failed to generate PR description');
              console.error(error);
            }

      - name: Validate token changes
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              execSync('pnpm run validate', { stdio: 'inherit' });
            } catch (error) {
              core.setFailed('Token validation failed');
            }